import os
from dotenv import load_dotenv

load_dotenv()


INTACCT_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2FwaS5pbnRhY2N0LmNvbSIsImlhdCI6MTc3MjE4NzE5NiwiZXhwIjoxNzcyMjY5OTk2LCJjbGllbnRJZCI6IjE5Nzc1ZDk5OGZlN2JlYTFkOWRkLlNhZ2VfSW50YWNjdF9VSS5hcHAuc2FnZS5jb20iLCJjbnlJZCI6Ik1QX0lHQ19NdWx0aVRheC1wb2Q2LWFjMDMtTVAxIiwiY255S2V5IjoiNjAxMDAwMDAwMjIzMTYxIiwidXNlcklkIjoiZ2lyaXNoIiwidXNlcktleSI6IjgiLCJzZXNzaW9uSWQiOiJ0N0tuRzRNOENlWXJSa1V0ckd2M185ZUU1aXBFSExld2hZQzB1ZjVmSzBaRkxheHI5LU94NHVZciIsImVudGl0eUtleSI6IiIsImVudGl0eUlkIjoiIiwiYWlFbmFibGVkIjpmYWxzZX0.-aIzZhGCK0gElX8fdLqYC_gM-l8t8d3cVEWgGGySvYQ"
# INTACCT_TOKEN = os.getenv("INTACCT_TOKEN")
# INTACCT_FILTER_URL = os.getenv("INTACCT_FILTER_URL")

HEADERS = {
    "Authorization": f"Bearer {INTACCT_TOKEN}",
    "Content-Type": "application/json"
}
